### ISSUE TITLE
Rename Job template 'Params' to 'Parameters'

### ISSUE THREAD

**Issue by Paebbels** [pyTooling/Actions#12]
We use everywhere explicit and full names, except for the job `Params`.

I suggest to rename it to `Parameters`.

I think a user can still call the job `Params` in his workflow, but the template would have a full name.

----------
/cc @umarcor

**Comment by umarcor** [comment]
That is correct. This is a breaking change. However, since we are in v0, shall we do it "silently" and fix the repos that are using it?

**Comment by Paebbels** [comment]
I think, it's for now just us using it. We haven't advertised it yet.

**Comment by umarcor** [comment]
This was changed in #15. It will be effective when merged to main and after publishing a new tag.
