### ISSUE TITLE
Create PR from 'main' to 'r0', if main was tagged

### ISSUE THREAD

**Issue by Paebbels** [pyTooling/Actions#22]
Is it possible to auto create a PullRequest from `main` to `r0`, when main was tagged?

----------
/cc @umarcor

**Comment by Paebbels** [comment]
This action might do the job: https://github.com/marketplace/actions/create-pull-request

**Comment by umarcor** [comment]
We don't need an action or PR. It's just:

```
git checkout r0
git merge --no-ff "$TAG" -m "$TAG"
git push
```

The default token can do that, the same way we can update branch `gh-pages` automatically.

**Comment by umarcor** [comment]
Refs:

- https://github.com/hdl/containers/blob/9958d9372fb64ebf180971a5c6606669139d56f3/.github/workflows/doc.yml#L80
- https://github.com/ghdl/ghdl/blob/f32d77707a2639fed94978965b3a9690c2bf7904/.github/workflows/Test.yml#L597
