### ISSUE TITLE
StaticTypeCheck is broken

### ISSUE THREAD

**Issue by Paebbels** [pyTooling/Actions#23]
Pipeline: https://github.com/pyTooling/pyTooling.GenericPath/actions/runs/1586187355

> **Invalid workflow file : .github/workflows/Pipeline.yml#L78**
> The workflow is not valid. pyTooling/Actions/.github/workflows/StaticTypeCheck.yml@r0 (Line: 78, Col: 28): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.allow_failure pyTooling/Actions/.github/workflows/StaticTypeCheck.yml@r0 (Line: 78, Col: 28): Unexpected value '${{ inputs.allow_failure }}'

@umarcor any ideas, what's different for this input parameter? Is it the boolean type?

**Comment by umarcor** [comment]
I don't know. Maybe `continue-on-error` requires a literal, similar to https://github.com/actions/runner/issues/1479.

Anyway, I'll revert #16, and we'll bring it back later with a proper fix and testing.
