### ISSUE TITLE
New pipeline image

### ISSUE THREAD

**Issue by Paebbels** [pyTooling/Actions#42]
After so many modifications, we should update the pipeline image, right?

This is from https://github.com/pyTooling/pyTooling.CLIAbstraction/actions/runs/1909980383

![image](https://user-images.githubusercontent.com/956109/156031636-5353338b-f144-4190-8768-25272188058d.png)

**Comment by umarcor** [comment]
Updated in https://github.com/pyTooling/Actions/commit/562b28ee341f8597e7f589498d418109745e0374.
