### ISSUE TITLE
Uploading archives with releaser fails once in a while

### ISSUE THREAD

**Issue by epsilon-0** [pyTooling/Actions#49]
I am using the `releaser` action with `pyTooling/Actions/releaser@r0` and it seems to be failing at uploading archives every once in a while.

The github action where this behaviour is  observed - https://github.com/OBSD-Homelab/openbsd-builder/actions

Example of a failed run - https://github.com/OBSD-Homelab/openbsd-builder/runs/6928392293?check_suite_focus=true
Example of a passing run - https://github.com/OBSD-Homelab/openbsd-builder/runs/6944587241?check_suite_focus=true

Both runs are scheduled runs, daily at `0 0 * * *`, so there is no code change between the two actions.

Let me know what else I should add to this report.

**Comment by Paebbels** [comment]
This is a duplicate of #48, right?

**Comment by kikmon** [comment]
Looks very similar to it
Any progress on the retry support ?

**Comment by epsilon-0** [comment]
Kind of does. But I don't know what exactly is happening here.

**Comment by umarcor** [comment]
Let's track this issue in #48.
